# Generated by Django 4.2.3 on 2023-08-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_pledge_supporter_alter_project_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='dev_pledge',
        ),
        migrations.AddField(
            model_name='pledge',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
